"""Synthetic catalogue used by the seed script. All brands, stores and people are fictional."""

from __future__ import annotations

# (slug, name, parent_slug, icon, description)
CATEGORIES: list[tuple[str, str, str | None, str, str]] = [
    ("electronics", "Electronics", None, "cpu", "Computers, phones, audio and cameras"),
    ("laptops", "Laptops", "electronics", "laptop", "Notebooks for work, study, coding and gaming"),
    ("smartphones", "Smartphones", "electronics", "smartphone", "Unlocked phones and flagship devices"),
    ("audio", "Headphones & Audio", "electronics", "headphones", "Headphones, earbuds and speakers"),
    ("cameras", "Cameras", "electronics", "camera", "Mirrorless and compact cameras"),
    ("camera-accessories", "Camera Accessories", "electronics", "aperture", "Lenses, tripods, memory and bags"),
    ("wearables", "Wearables", "electronics", "watch", "Smartwatches and fitness trackers"),
    ("computer-accessories", "Computer Accessories", "electronics", "keyboard", "Keyboards, mice, hubs and monitors"),
    ("fashion", "Fashion", None, "shirt", "Shoes, apparel and accessories"),
    ("running-shoes", "Running Shoes", "fashion", "footprints", "Road and trail running shoes"),
    ("outerwear", "Jackets & Outerwear", "fashion", "shirt", "Jackets, rain shells and parkas"),
    ("bags", "Bags & Backpacks", "fashion", "backpack", "Backpacks, totes and travel bags"),
    ("home-kitchen", "Home & Kitchen", None, "home", "Appliances, cookware and furniture"),
    ("kitchen-appliances", "Kitchen Appliances", "home-kitchen", "chef-hat", "Coffee makers, blenders and more"),
    ("furniture", "Furniture", "home-kitchen", "sofa", "Desks, chairs and living room"),
    ("sports-outdoors", "Sports & Outdoors", None, "dumbbell", "Fitness, yoga and camping gear"),
    ("fitness", "Fitness & Yoga", "sports-outdoors", "dumbbell", "Home gym and yoga essentials"),
    ("camping", "Camping & Hiking", "sports-outdoors", "tent", "Tents, sleeping bags and trail gear"),
    ("beauty", "Beauty & Personal Care", None, "sparkles", "Skincare and grooming"),
    ("books", "Books & Stationery", None, "book-open", "Books, notebooks and pens"),
    ("toys", "Toys & Games", None, "puzzle", "Board games, building sets and puzzles"),
]

# Accessory categories that complement a product category (used by bundles/accessory workflows).
COMPLEMENTS: dict[str, list[str]] = {
    "cameras": ["camera-accessories"],
    "laptops": ["computer-accessories", "bags", "audio"],
    "smartphones": ["audio", "wearables"],
    "running-shoes": ["wearables", "fitness"],
    "fitness": ["wearables", "running-shoes"],
    "camping": ["bags", "outerwear"],
}

# (store_name, owner_full_name, email_local, description, negotiation_enabled)
SELLERS: list[tuple[str, str, str, str, bool]] = [
    ("Voltrix Official", "Maya Chen", "voltrix", "Official store for Voltrix laptops and accessories.", True),
    ("Kestrel Computing", "Daniel Okafor", "kestrel", "Performance laptops and gaming gear.", False),
    ("Lumen Mobile", "Priya Raman", "lumen", "Smartphones and wearables, shipped fast.", True),
    ("SonicWave Audio", "Lucas Moreau", "sonicwave", "Headphones and speakers tuned by audio engineers.", True),
    ("Aperture House", "Hana Suzuki", "aperture", "Cameras, lenses and everything for photographers.", True),
    ("Stridewell", "Marcus Bell", "stridewell", "Running shoes engineered for every distance.", False),
    ("Northpeak Outfitters", "Elena Petrova", "northpeak", "Outdoor apparel, packs and camping gear.", True),
    ("Hearth & Co", "Samuel Adeyemi", "hearth", "Kitchen appliances for everyday cooks.", False),
    ("Oakline Furniture", "Grace Kim", "oakline", "Solid-wood desks and ergonomic seating.", True),
    ("FlexFit Studio", "Omar Haddad", "flexfit", "Home fitness and yoga equipment.", True),
    ("Glow Botanics", "Chloe Martin", "glow", "Clean skincare made in small batches.", False),
    ("Inkwell & Play", "Noah Fischer", "inkwell", "Books, stationery and family games.", False),
]

# Each product: category, seller index, name, brand, price, sale_price, attributes, tags, blurb
PRODUCTS: list[dict] = [
    # ---- Laptops ----
    dict(cat="laptops", s=0, name="Voltrix AeroBook 14", brand="Voltrix", price=899, sale=849,
         attrs={"cpu": "Ryzen 7 7840U", "ram_gb": 16, "storage_gb": 512, "display": "14\" 2.8K 120Hz OLED", "weight_kg": 1.3, "battery_hours": 14, "os": "Windows 11"},
         tags=["laptop", "programming", "ultralight", "oled"], blurb="A featherweight 14-inch laptop with a vivid OLED panel and all-day battery — ideal for developers and students."),
    dict(cat="laptops", s=0, name="Voltrix AeroBook Pro 16", brand="Voltrix", price=1499, sale=None,
         attrs={"cpu": "Core Ultra 9", "ram_gb": 32, "storage_gb": 1024, "display": "16\" 3.2K 165Hz", "gpu": "RTX 4060", "weight_kg": 2.1, "battery_hours": 10, "os": "Windows 11"},
         tags=["laptop", "programming", "creator", "video-editing"], blurb="Workstation-class power for compiling, containers, and 4K video editing."),
    dict(cat="laptops", s=0, name="Voltrix AeroBook 13 Air", brand="Voltrix", price=749, sale=699,
         attrs={"cpu": "Core Ultra 5", "ram_gb": 16, "storage_gb": 512, "display": "13.3\" 2K IPS", "weight_kg": 1.1, "battery_hours": 16, "os": "Windows 11"},
         tags=["laptop", "student", "ultralight"], blurb="Fanless, silent and light — the everyday laptop for study and travel."),
    dict(cat="laptops", s=1, name="Kestrel Forge 15 Gaming Laptop", brand="Kestrel", price=1299, sale=1199,
         attrs={"cpu": "Ryzen 9 7945HX", "ram_gb": 32, "storage_gb": 1024, "display": "15.6\" QHD 240Hz", "gpu": "RTX 4070", "weight_kg": 2.4, "battery_hours": 6, "os": "Windows 11"},
         tags=["laptop", "gaming", "rgb", "high-refresh"], blurb="A 240Hz esports machine with RTX 4070 graphics and a vapour-chamber cooler."),
    dict(cat="laptops", s=1, name="Kestrel Slate 13 Ultrabook", brand="Kestrel", price=1049, sale=None,
         attrs={"cpu": "Core Ultra 7", "ram_gb": 16, "storage_gb": 1024, "display": "13.5\" 3K touch", "weight_kg": 1.2, "battery_hours": 13, "os": "Windows 11"},
         tags=["laptop", "business", "touchscreen", "ultralight"], blurb="Premium aluminium ultrabook with a 3:2 touch display for productivity."),
    dict(cat="laptops", s=1, name="Kestrel DevBook 14 Linux Edition", brand="Kestrel", price=949, sale=None,
         attrs={"cpu": "Ryzen 7 7840HS", "ram_gb": 32, "storage_gb": 1024, "display": "14\" 2.5K matte", "weight_kg": 1.5, "battery_hours": 11, "os": "Ubuntu 24.04 LTS"},
         tags=["laptop", "programming", "linux", "developer"], blurb="Ships with Ubuntu preinstalled, 32GB RAM and a best-in-class keyboard for coders."),
    dict(cat="laptops", s=0, name="Voltrix StudyBook 15", brand="Voltrix", price=549, sale=499,
         attrs={"cpu": "Core i5-1335U", "ram_gb": 8, "storage_gb": 256, "display": "15.6\" FHD", "weight_kg": 1.7, "battery_hours": 9, "os": "Windows 11"},
         tags=["laptop", "student", "budget"], blurb="An affordable 15-inch laptop for schoolwork, streaming and browsing."),
    dict(cat="laptops", s=1, name="Kestrel Nimbus Chromebook 14", brand="Kestrel", price=329, sale=279,
         attrs={"cpu": "MediaTek Kompanio 1380", "ram_gb": 8, "storage_gb": 128, "display": "14\" FHD", "weight_kg": 1.4, "battery_hours": 12, "os": "ChromeOS"},
         tags=["laptop", "chromebook", "budget", "student"], blurb="Fast, secure ChromeOS laptop with all-day battery at a budget price."),
    # ---- Computer accessories ----
    dict(cat="computer-accessories", s=0, name="Voltrix TypeFlow Mechanical Keyboard", brand="Voltrix", price=129, sale=109,
         attrs={"switches": "tactile brown", "layout": "75%", "connectivity": "USB-C / Bluetooth", "compatible_with": ["laptop", "desktop"]},
         tags=["keyboard", "mechanical", "programming"], blurb="Hot-swappable 75% mechanical keyboard with a gasket mount for a quiet, cushioned feel."),
    dict(cat="computer-accessories", s=0, name="Voltrix Glide Wireless Mouse", brand="Voltrix", price=59, sale=None,
         attrs={"dpi": 8000, "connectivity": "Bluetooth / 2.4GHz", "battery_days": 70, "compatible_with": ["laptop", "desktop"]},
         tags=["mouse", "wireless", "ergonomic"], blurb="Ergonomic wireless mouse with silent clicks and a 70-day battery."),
    dict(cat="computer-accessories", s=1, name="Kestrel 8-in-1 USB-C Hub", brand="Kestrel", price=49, sale=39,
         attrs={"ports": "HDMI 4K60, 3x USB-A, SD, microSD, Ethernet, 100W PD", "compatible_with": ["laptop"]},
         tags=["usb-c", "hub", "dock"], blurb="Expand a thin laptop into a full desk setup with one cable."),
    dict(cat="computer-accessories", s=1, name="Kestrel View 27 4K Monitor", brand="Kestrel", price=379, sale=None,
         attrs={"size_in": 27, "resolution": "3840x2160", "panel": "IPS", "refresh_hz": 60, "usb_c_pd_w": 65},
         tags=["monitor", "4k", "programming", "usb-c"], blurb="Sharp 4K IPS monitor with single-cable USB-C charging for laptops."),
    # ---- Smartphones ----
    dict(cat="smartphones", s=2, name="Lumen Nova X Pro", brand="Lumen", price=999, sale=949,
         attrs={"storage_gb": 256, "display": "6.7\" LTPO OLED 120Hz", "camera_mp": 50, "battery_mah": 5000, "5g": True},
         tags=["phone", "flagship", "5g", "camera-phone"], blurb="Flagship phone with a triple 50MP camera system and two-day battery."),
    dict(cat="smartphones", s=2, name="Lumen Nova X", brand="Lumen", price=799, sale=None,
         attrs={"storage_gb": 128, "display": "6.3\" OLED 120Hz", "camera_mp": 50, "battery_mah": 4600, "5g": True},
         tags=["phone", "5g", "compact"], blurb="Compact flagship performance in a one-handed size."),
    dict(cat="smartphones", s=2, name="Lumen Aura A5", brand="Lumen", price=349, sale=299,
         attrs={"storage_gb": 128, "display": "6.5\" OLED 90Hz", "camera_mp": 64, "battery_mah": 5000, "5g": True},
         tags=["phone", "budget", "5g"], blurb="Midrange 5G phone with an OLED screen and big battery."),
    dict(cat="smartphones", s=2, name="Lumen Fold Flex", brand="Lumen", price=1599, sale=None,
         attrs={"storage_gb": 512, "display": "7.6\" foldable OLED", "camera_mp": 50, "battery_mah": 4400, "5g": True},
         tags=["phone", "foldable", "flagship"], blurb="A foldable that becomes a tablet for multitasking on the go."),
    dict(cat="smartphones", s=2, name="Lumen Rugged R2", brand="Lumen", price=449, sale=None,
         attrs={"storage_gb": 128, "display": "6.1\" LCD", "ip_rating": "IP69K", "battery_mah": 6500, "5g": False},
         tags=["phone", "rugged", "outdoor"], blurb="Drop-proof, waterproof phone for job sites and trails."),
    # ---- Audio ----
    dict(cat="audio", s=3, name="SonicWave Quiet 900 Headphones", brand="SonicWave", price=349, sale=299,
         attrs={"type": "over-ear", "anc": True, "battery_hours": 40, "connectivity": "Bluetooth 5.3", "weight_g": 250},
         tags=["headphones", "noise-cancelling", "travel", "wireless"], blurb="Industry-leading noise cancelling with 40 hours of playback."),
    dict(cat="audio", s=3, name="SonicWave Buds Pro 2", brand="SonicWave", price=199, sale=169,
         attrs={"type": "in-ear", "anc": True, "battery_hours": 8, "water_resistance": "IPX5"},
         tags=["earbuds", "noise-cancelling", "wireless", "workout"], blurb="True wireless earbuds with adaptive ANC and a secure sport fit."),
    dict(cat="audio", s=3, name="SonicWave Studio Monitor Headphones", brand="SonicWave", price=159, sale=None,
         attrs={"type": "over-ear", "anc": False, "impedance_ohm": 38, "connectivity": "3.5mm wired"},
         tags=["headphones", "studio", "wired"], blurb="Flat, accurate sound for mixing, podcasting and critical listening."),
    dict(cat="audio", s=3, name="SonicWave Boom Mini Speaker", brand="SonicWave", price=79, sale=69,
         attrs={"battery_hours": 16, "water_resistance": "IP67", "connectivity": "Bluetooth 5.3"},
         tags=["speaker", "portable", "waterproof"], blurb="Pocketable waterproof speaker with surprisingly deep bass."),
    dict(cat="audio", s=2, name="Lumen Buds Lite", brand="Lumen", price=59, sale=None,
         attrs={"type": "in-ear", "anc": False, "battery_hours": 7, "water_resistance": "IPX4"},
         tags=["earbuds", "budget", "wireless"], blurb="Everyday wireless earbuds at an easy price."),
    dict(cat="audio", s=3, name="SonicWave Arc Soundbar", brand="SonicWave", price=449, sale=399,
         attrs={"channels": "5.1.2", "dolby_atmos": True, "connectivity": "HDMI eARC / Wi-Fi"},
         tags=["soundbar", "home-theater", "speaker"], blurb="Room-filling Dolby Atmos soundbar with upfiring drivers."),
    # ---- Cameras ----
    dict(cat="cameras", s=4, name="Aperture Lumix LX-7 Mirrorless Camera", brand="Aperture", price=1199, sale=1099,
         attrs={"sensor": "APS-C 26MP", "mount": "LX-mount", "video": "4K60", "ibis": True, "weight_g": 450},
         tags=["camera", "mirrorless", "vlogging", "4k"], blurb="Compact APS-C mirrorless camera with in-body stabilisation and 4K60 video."),
    dict(cat="cameras", s=4, name="Aperture LX-9 Full-Frame Camera", brand="Aperture", price=2299, sale=None,
         attrs={"sensor": "Full-frame 33MP", "mount": "LX-mount", "video": "4K120", "ibis": True, "weight_g": 650},
         tags=["camera", "mirrorless", "full-frame", "professional"], blurb="Full-frame hybrid camera for professional stills and cinematic video."),
    dict(cat="cameras", s=4, name="Aperture Snap C3 Compact Camera", brand="Aperture", price=549, sale=499,
         attrs={"sensor": "1-inch 20MP", "mount": "fixed lens", "video": "4K30", "zoom": "24-120mm"},
         tags=["camera", "compact", "travel"], blurb="Pocket-sized premium compact with a bright 5x zoom lens."),
    dict(cat="cameras", s=4, name="Aperture ActionCam 5", brand="Aperture", price=329, sale=None,
         attrs={"video": "5.3K60", "waterproof_m": 10, "stabilization": "HyperSmooth", "mount": "action-mount"},
         tags=["camera", "action", "waterproof"], blurb="Rugged action camera with gimbal-like stabilisation."),
    # ---- Camera accessories ----
    dict(cat="camera-accessories", s=4, name="Aperture 35mm f/1.8 Prime Lens (LX-mount)", brand="Aperture", price=399, sale=349,
         attrs={"focal_length": "35mm", "aperture": "f/1.8", "compatible_mounts": ["LX-mount"]},
         tags=["lens", "prime", "portrait"], blurb="Sharp, fast everyday prime lens with silky background blur."),
    dict(cat="camera-accessories", s=4, name="Aperture 18-135mm Zoom Lens (LX-mount)", brand="Aperture", price=599, sale=None,
         attrs={"focal_length": "18-135mm", "aperture": "f/3.5-5.6", "stabilized": True, "compatible_mounts": ["LX-mount"]},
         tags=["lens", "zoom", "travel"], blurb="Versatile stabilised travel zoom covering wide to telephoto."),
    dict(cat="camera-accessories", s=4, name="Aperture TravelPod Carbon Tripod", brand="Aperture", price=189, sale=159,
         attrs={"material": "carbon fibre", "max_load_kg": 8, "weight_kg": 1.2, "compatible_with": ["camera"]},
         tags=["tripod", "travel", "carbon"], blurb="Lightweight carbon tripod that folds to 40cm."),
    dict(cat="camera-accessories", s=4, name="Aperture ProCard 128GB V60 SD Card", brand="Aperture", price=49, sale=None,
         attrs={"capacity_gb": 128, "speed_class": "V60", "compatible_with": ["camera"]},
         tags=["memory-card", "sd", "4k"], blurb="Fast V60 SD card rated for 4K video recording."),
    dict(cat="camera-accessories", s=4, name="Aperture LX Spare Battery", brand="Aperture", price=59, sale=None,
         attrs={"capacity_mah": 2280, "compatible_mounts": ["LX-mount"]},
         tags=["battery", "camera"], blurb="Genuine spare battery for LX-series camera bodies."),
    dict(cat="camera-accessories", s=6, name="Northpeak Sling Camera Bag 10L", brand="Northpeak", price=89, sale=79,
         attrs={"capacity_l": 10, "weatherproof": True, "compatible_with": ["camera"]},
         tags=["camera-bag", "sling", "travel"], blurb="Weatherproof sling that fits a mirrorless body and two lenses."),
    # ---- Wearables ----
    dict(cat="wearables", s=2, name="Lumen Pulse Watch 3", brand="Lumen", price=299, sale=249,
         attrs={"display": "1.4\" AMOLED", "gps": True, "battery_days": 7, "water_resistance": "5ATM"},
         tags=["smartwatch", "fitness", "gps", "running"], blurb="Smartwatch with dual-band GPS, heart-rate and sleep tracking."),
    dict(cat="wearables", s=2, name="Lumen Band Fit", brand="Lumen", price=79, sale=None,
         attrs={"display": "AMOLED", "gps": False, "battery_days": 14},
         tags=["fitness-tracker", "budget", "sleep"], blurb="Slim fitness band that tracks steps, sleep and stress."),
    dict(cat="wearables", s=9, name="FlexFit Stride GPS Running Watch", brand="FlexFit", price=229, sale=199,
         attrs={"gps": True, "battery_days": 12, "running_dynamics": True, "water_resistance": "5ATM"},
         tags=["running", "gps", "watch", "training"], blurb="Training-focused GPS watch with pace coaching and recovery insights."),
    # ---- Running shoes ----
    dict(cat="running-shoes", s=5, name="Stridewell Velocity 3 Road Running Shoe", brand="Stridewell", price=139, sale=119,
         attrs={"drop_mm": 8, "weight_g": 240, "cushioning": "high", "surface": "road", "sizes": ["7", "8", "9", "10", "11", "12"]},
         tags=["running", "shoe", "road", "daily-trainer"], blurb="Plush, responsive daily trainer for easy miles and long runs."),
    dict(cat="running-shoes", s=5, name="Stridewell Carbon Race Elite", brand="Stridewell", price=249, sale=None,
         attrs={"drop_mm": 8, "weight_g": 195, "plate": "carbon", "surface": "road", "sizes": ["7", "8", "9", "10", "11"]},
         tags=["running", "shoe", "racing", "marathon", "carbon-plate"], blurb="Carbon-plated super shoe built for race-day PRs."),
    dict(cat="running-shoes", s=5, name="Stridewell TrailGrip GTX", brand="Stridewell", price=159, sale=139,
         attrs={"drop_mm": 6, "weight_g": 290, "waterproof": True, "surface": "trail", "lug_mm": 5},
         tags=["running", "shoe", "trail", "waterproof"], blurb="Waterproof trail runner with aggressive 5mm lugs."),
    dict(cat="running-shoes", s=5, name="Stridewell Glide Stability", brand="Stridewell", price=129, sale=None,
         attrs={"drop_mm": 10, "weight_g": 270, "support": "stability", "surface": "road"},
         tags=["running", "shoe", "stability", "overpronation"], blurb="Supportive stability shoe for runners who overpronate."),
    dict(cat="running-shoes", s=5, name="Stridewell Everyday Runner", brand="Stridewell", price=79, sale=69,
         attrs={"drop_mm": 10, "weight_g": 260, "cushioning": "medium", "surface": "road"},
         tags=["running", "shoe", "budget", "beginner"], blurb="Comfortable, durable running shoe for new runners."),
    dict(cat="running-shoes", s=9, name="FlexFit Tempo Trainer", brand="FlexFit", price=109, sale=None,
         attrs={"drop_mm": 6, "weight_g": 225, "cushioning": "medium", "surface": "road"},
         tags=["running", "shoe", "tempo", "gym"], blurb="Lightweight shoe for tempo runs and gym sessions."),
    # ---- Outerwear ----
    dict(cat="outerwear", s=6, name="Northpeak Stormline Rain Jacket", brand="Northpeak", price=179, sale=149,
         attrs={"waterproof_mm": 20000, "breathability_g": 20000, "weight_g": 310, "packable": True},
         tags=["jacket", "rain", "hiking", "waterproof"], blurb="3-layer waterproof shell that packs into its own pocket."),
    dict(cat="outerwear", s=6, name="Northpeak Summit Down Parka", brand="Northpeak", price=329, sale=None,
         attrs={"fill_power": 800, "temperature_rating_c": -20, "hood": True},
         tags=["jacket", "winter", "down", "parka"], blurb="Expedition-warm 800-fill down parka for deep winter."),
    dict(cat="outerwear", s=6, name="Northpeak Trailhead Fleece", brand="Northpeak", price=89, sale=69,
         attrs={"material": "recycled polyester fleece", "weight_g": 380},
         tags=["fleece", "layering", "hiking"], blurb="Cozy recycled fleece for cool mornings on the trail."),
    dict(cat="outerwear", s=5, name="Stridewell Wind Runner Jacket", brand="Stridewell", price=99, sale=None,
         attrs={"weight_g": 120, "reflective": True, "packable": True},
         tags=["jacket", "running", "windproof", "reflective"], blurb="Featherweight windproof running jacket with reflective details."),
    # ---- Bags ----
    dict(cat="bags", s=6, name="Northpeak Commuter Laptop Backpack 24L", brand="Northpeak", price=119, sale=99,
         attrs={"capacity_l": 24, "laptop_sleeve_in": 16, "water_resistant": True},
         tags=["backpack", "laptop", "commuter"], blurb="Organised commuter pack with a padded 16\" laptop sleeve."),
    dict(cat="bags", s=6, name="Northpeak Ridge 45L Hiking Pack", brand="Northpeak", price=189, sale=None,
         attrs={"capacity_l": 45, "frame": "internal", "hydration_compatible": True},
         tags=["backpack", "hiking", "trekking"], blurb="Ventilated 45L pack for multi-day treks."),
    dict(cat="bags", s=0, name="Voltrix Slim Laptop Sleeve 14\"", brand="Voltrix", price=39, sale=None,
         attrs={"fits_in": 14, "material": "recycled felt"},
         tags=["laptop-sleeve", "laptop", "minimal"], blurb="Minimal felt sleeve that protects a 14\" laptop."),
    dict(cat="bags", s=9, name="FlexFit Gym Duffel 35L", brand="FlexFit", price=69, sale=59,
         attrs={"capacity_l": 35, "shoe_compartment": True},
         tags=["duffel", "gym", "travel"], blurb="Gym duffel with a ventilated shoe compartment."),
    # ---- Kitchen ----
    dict(cat="kitchen-appliances", s=7, name="Hearth BrewMaster Espresso Machine", brand="Hearth", price=499, sale=449,
         attrs={"pressure_bar": 15, "grinder": "built-in conical burr", "milk_frother": True},
         tags=["espresso", "coffee", "kitchen"], blurb="Bean-to-cup espresso with a built-in burr grinder and steam wand."),
    dict(cat="kitchen-appliances", s=7, name="Hearth PowerBlend 1200 Blender", brand="Hearth", price=149, sale=None,
         attrs={"power_w": 1200, "capacity_l": 2, "programs": 6},
         tags=["blender", "smoothie", "kitchen"], blurb="High-speed blender for smoothies, soups and nut butters."),
    dict(cat="kitchen-appliances", s=7, name="Hearth AirCrisp 6QT Air Fryer", brand="Hearth", price=129, sale=99,
         attrs={"capacity_qt": 6, "power_w": 1700, "presets": 8},
         tags=["air-fryer", "healthy", "kitchen"], blurb="Crispy results with little to no oil and 8 one-touch presets."),
    dict(cat="kitchen-appliances", s=7, name="Hearth PourOver Kettle", brand="Hearth", price=79, sale=None,
         attrs={"capacity_l": 0.9, "temperature_control": True},
         tags=["kettle", "coffee", "tea"], blurb="Gooseneck kettle with precise temperature control."),
    dict(cat="kitchen-appliances", s=7, name="Hearth SmartCook Multicooker", brand="Hearth", price=159, sale=139,
         attrs={"capacity_l": 6, "functions": 12, "wifi": True},
         tags=["pressure-cooker", "slow-cooker", "kitchen"], blurb="12-in-1 pressure cooker with app-guided recipes."),
    dict(cat="kitchen-appliances", s=7, name="Hearth Pro Chef Knife Set", brand="Hearth", price=199, sale=None,
         attrs={"pieces": 7, "steel": "German X50CrMoV15"},
         tags=["knives", "cookware", "kitchen"], blurb="Forged German-steel knife set with a walnut block."),
    # ---- Furniture ----
    dict(cat="furniture", s=8, name="Oakline Lift Standing Desk", brand="Oakline", price=549, sale=499,
         attrs={"width_cm": 140, "height_range_cm": "65-130", "motors": 2, "top": "solid oak"},
         tags=["desk", "standing-desk", "home-office"], blurb="Dual-motor standing desk with a solid oak top and memory presets."),
    dict(cat="furniture", s=8, name="Oakline Ergo Mesh Chair", brand="Oakline", price=399, sale=None,
         attrs={"lumbar_support": "adjustable", "armrests": "4D", "max_load_kg": 135},
         tags=["chair", "ergonomic", "home-office"], blurb="Breathable mesh office chair with adjustable lumbar support."),
    dict(cat="furniture", s=8, name="Oakline Nordic Bookshelf", brand="Oakline", price=229, sale=199,
         attrs={"shelves": 5, "material": "oak veneer", "height_cm": 180},
         tags=["bookshelf", "storage", "living-room"], blurb="Five-shelf Scandinavian bookshelf in warm oak."),
    dict(cat="furniture", s=8, name="Oakline Monitor Riser", brand="Oakline", price=59, sale=None,
         attrs={"material": "walnut", "width_cm": 60},
         tags=["desk-accessory", "home-office", "ergonomic"], blurb="Solid walnut riser that lifts your monitor to eye level."),
    # ---- Fitness & yoga ----
    dict(cat="fitness", s=9, name="FlexFit Adjustable Dumbbells 24kg", brand="FlexFit", price=299, sale=269,
         attrs={"weight_range_kg": "2.5-24", "increments": 15},
         tags=["dumbbells", "strength", "home-gym"], blurb="Replace 15 pairs of dumbbells with one compact set."),
    dict(cat="fitness", s=9, name="FlexFit ProGrip Yoga Mat 6mm", brand="FlexFit", price=69, sale=None,
         attrs={"thickness_mm": 6, "material": "natural rubber", "non_slip": True},
         tags=["yoga", "mat", "pilates"], blurb="Grippy natural-rubber yoga mat with alignment lines."),
    dict(cat="fitness", s=9, name="FlexFit Resistance Band Set", brand="FlexFit", price=29, sale=24,
         attrs={"bands": 5, "max_resistance_kg": 60},
         tags=["resistance-bands", "strength", "travel"], blurb="Five colour-coded bands for full-body workouts anywhere."),
    dict(cat="fitness", s=9, name="FlexFit Cork Yoga Block Pair", brand="FlexFit", price=25, sale=None,
         attrs={"material": "cork", "count": 2},
         tags=["yoga", "block", "pilates"], blurb="Sustainable cork blocks for support and alignment."),
    dict(cat="fitness", s=9, name="FlexFit Foam Roller", brand="FlexFit", price=35, sale=None,
         attrs={"length_cm": 45, "density": "firm"},
         tags=["recovery", "foam-roller", "running"], blurb="Firm textured roller for post-run recovery."),
    # ---- Camping ----
    dict(cat="camping", s=6, name="Northpeak Basecamp 2P Tent", brand="Northpeak", price=279, sale=239,
         attrs={"capacity_people": 2, "weight_kg": 1.9, "season": "3-season"},
         tags=["tent", "backpacking", "camping"], blurb="Freestanding 3-season tent that pitches in minutes."),
    dict(cat="camping", s=6, name="Northpeak Ember -5°C Sleeping Bag", brand="Northpeak", price=199, sale=None,
         attrs={"comfort_c": -5, "fill": "synthetic", "weight_kg": 1.4},
         tags=["sleeping-bag", "camping", "winter"], blurb="Warm synthetic mummy bag that performs when damp."),
    dict(cat="camping", s=6, name="Northpeak TrailLite Headlamp", brand="Northpeak", price=45, sale=39,
         attrs={"lumens": 400, "rechargeable": True, "water_resistance": "IPX6"},
         tags=["headlamp", "hiking", "camping"], blurb="Rechargeable 400-lumen headlamp with red night mode."),
    dict(cat="camping", s=6, name="Northpeak Titanium Cook Kit", brand="Northpeak", price=89, sale=None,
         attrs={"material": "titanium", "pieces": 4, "weight_g": 210},
         tags=["cookware", "backpacking", "camping"], blurb="Ultralight titanium pot and pan set."),
    # ---- Beauty ----
    dict(cat="beauty", s=10, name="Glow Botanics Hydra Serum", brand="Glow Botanics", price=38, sale=32,
         attrs={"volume_ml": 30, "key_ingredients": ["hyaluronic acid", "niacinamide"], "skin_type": "all"},
         tags=["serum", "skincare", "hydrating"], blurb="Lightweight serum that plumps and hydrates all skin types."),
    dict(cat="beauty", s=10, name="Glow Botanics Daily Mineral SPF 50", brand="Glow Botanics", price=29, sale=None,
         attrs={"volume_ml": 50, "spf": 50, "reef_safe": True},
         tags=["sunscreen", "skincare", "spf"], blurb="Sheer mineral sunscreen with no white cast."),
    dict(cat="beauty", s=10, name="Glow Botanics Barrier Repair Moisturizer", brand="Glow Botanics", price=42, sale=None,
         attrs={"volume_ml": 50, "key_ingredients": ["ceramides", "squalane"], "fragrance_free": True},
         tags=["moisturizer", "skincare", "sensitive-skin"], blurb="Rich ceramide cream that restores a stressed skin barrier."),
    dict(cat="beauty", s=10, name="Glow Botanics Gentle Gel Cleanser", brand="Glow Botanics", price=24, sale=19,
         attrs={"volume_ml": 150, "ph_balanced": True},
         tags=["cleanser", "skincare"], blurb="pH-balanced gel cleanser that never feels tight."),
    # ---- Books ----
    dict(cat="books", s=11, name="The Pragmatic Pipeline: Shipping Software Calmly", brand="Inkwell Press", price=39, sale=None,
         attrs={"format": "hardcover", "pages": 384, "topic": "software engineering"},
         tags=["book", "programming", "software"], blurb="A practical guide to reliable delivery pipelines and team habits."),
    dict(cat="books", s=11, name="Data Stories: Practical Analytics", brand="Inkwell Press", price=34, sale=29,
         attrs={"format": "paperback", "pages": 296, "topic": "data science"},
         tags=["book", "data", "analytics"], blurb="Hands-on analytics and visualisation techniques with real datasets."),
    dict(cat="books", s=11, name="Inkwell Dot Grid Notebook A5", brand="Inkwell", price=18, sale=None,
         attrs={"pages": 192, "paper_gsm": 120},
         tags=["notebook", "stationery", "journal"], blurb="Fountain-pen friendly dot-grid notebook with lay-flat binding."),
    dict(cat="books", s=11, name="Inkwell Fineliner Pen Set", brand="Inkwell", price=15, sale=12,
         attrs={"count": 12, "tip_mm": 0.4},
         tags=["pens", "stationery", "drawing"], blurb="Twelve archival-ink fineliners in vivid colours."),
    # ---- Toys ----
    dict(cat="toys", s=11, name="Inkwell Settlers of the Isles Board Game", brand="Inkwell Games", price=49, sale=None,
         attrs={"players": "3-4", "age": "10+", "playtime_min": 60},
         tags=["board-game", "strategy", "family"], blurb="Trade, build and settle a modular island in this family strategy game."),
    dict(cat="toys", s=11, name="Inkwell 1000-Piece Mountain Puzzle", brand="Inkwell Games", price=22, sale=18,
         attrs={"pieces": 1000, "age": "12+"},
         tags=["puzzle", "jigsaw", "family"], blurb="A panoramic alpine landscape printed on thick recycled board."),
    dict(cat="toys", s=11, name="Inkwell Robo Builder STEM Kit", brand="Inkwell Games", price=89, sale=79,
         attrs={"age": "8+", "programmable": True, "pieces": 320},
         tags=["stem", "robotics", "kids", "coding"], blurb="Build and code five robots with a kid-friendly block language."),
    dict(cat="toys", s=11, name="Inkwell Party Trivia Night", brand="Inkwell Games", price=29, sale=None,
         attrs={"players": "4-12", "age": "14+"},
         tags=["party-game", "trivia", "family"], blurb="1,500 questions for game nights with friends."),
]

BUNDLES: list[dict] = [
    dict(name="LX-7 Creator Kit", seller=4, discount=("percentage", 12),
         products=["Aperture Lumix LX-7 Mirrorless Camera", "Aperture 35mm f/1.8 Prime Lens (LX-mount)",
                   "Aperture ProCard 128GB V60 SD Card", "Aperture LX Spare Battery"],
         description="Everything a new creator needs: body, fast prime, memory and a spare battery."),
    dict(name="Photographer's Travel Set", seller=4, discount=("fixed", 60),
         products=["Aperture 18-135mm Zoom Lens (LX-mount)", "Aperture TravelPod Carbon Tripod",
                   "Aperture ProCard 128GB V60 SD Card"],
         description="Travel zoom, carbon tripod and a fast card for trips."),
    dict(name="Developer Desk Setup", seller=0, discount=("percentage", 10),
         products=["Voltrix AeroBook 14", "Voltrix TypeFlow Mechanical Keyboard", "Voltrix Glide Wireless Mouse",
                   "Voltrix Slim Laptop Sleeve 14\""],
         description="The AeroBook 14 plus a mechanical keyboard, mouse and sleeve."),
    dict(name="Race Day Pack", seller=5, discount=("percentage", 15),
         products=["Stridewell Carbon Race Elite", "Stridewell Wind Runner Jacket"],
         description="Carbon racers plus a packable wind jacket for race morning."),
    dict(name="Yoga Starter Bundle", seller=9, discount=("percentage", 15),
         products=["FlexFit ProGrip Yoga Mat 6mm", "FlexFit Cork Yoga Block Pair", "FlexFit Resistance Band Set"],
         description="Mat, blocks and bands to start a home practice."),
    dict(name="Weekend Backpacking Kit", seller=6, discount=("fixed", 50),
         products=["Northpeak Basecamp 2P Tent", "Northpeak Ember -5°C Sleeping Bag", "Northpeak TrailLite Headlamp"],
         description="Shelter, sleep and light for a weekend on the trail."),
    dict(name="Coffee Lover's Duo", seller=7, discount=("percentage", 8),
         products=["Hearth BrewMaster Espresso Machine", "Hearth PourOver Kettle"],
         description="Espresso and pour-over, covered."),
    dict(name="Daily Skincare Routine", seller=10, discount=("percentage", 10),
         products=["Glow Botanics Gentle Gel Cleanser", "Glow Botanics Hydra Serum",
                   "Glow Botanics Barrier Repair Moisturizer", "Glow Botanics Daily Mineral SPF 50"],
         description="Cleanse, treat, moisturise and protect."),
]

# Review language per root category: (positive aspects, negative aspects)
REVIEW_ASPECTS: dict[str, tuple[list[str], list[str]]] = {
    "electronics": (
        ["battery life is excellent", "build quality feels premium", "the screen is bright and sharp",
         "performance is snappy even with many apps open", "setup took five minutes", "great value for the price",
         "sound quality is rich and detailed", "very lightweight and easy to carry"],
        ["battery drains faster than advertised", "it gets warm under load", "the charger is bulky",
         "fan noise is noticeable", "software had a few bugs out of the box", "customer support was slow",
         "the price is a bit high", "fingerprints show up easily"],
    ),
    "fashion": (
        ["very comfortable from the first wear", "fits true to size", "looks even better in person",
         "materials feel durable", "great grip and support", "lightweight and breathable"],
        ["runs a half size small", "the colour is slightly different from the photos", "stitching came loose",
         "a bit stiff at first", "not as waterproof as expected", "sizing is inconsistent"],
    ),
    "home-kitchen": (
        ["easy to clean", "sturdy and well built", "assembly was straightforward", "looks great in my kitchen",
         "heats up quickly", "worth every penny"],
        ["louder than expected", "instructions were confusing", "arrived with a small scratch",
         "takes up a lot of counter space", "one part broke after a month", "assembly took hours"],
    ),
    "sports-outdoors": (
        ["held up great on the trail", "lightweight and packs small", "excellent grip", "very stable",
         "great quality for the price", "kept me warm and dry"],
        ["zipper feels flimsy", "heavier than listed", "smell out of the box", "sizing chart was off",
         "not durable for heavy use"],
    ),
    "beauty": (
        ["skin feels hydrated all day", "no irritation on sensitive skin", "absorbs quickly",
         "a little goes a long way", "gentle and effective"],
        ["broke me out", "the pump stopped working", "small bottle for the price", "scent is too strong"],
    ),
    "books": (
        ["clear and practical writing", "beautiful paper quality", "great gift", "well organised chapters"],
        ["too basic for experienced readers", "binding is weak", "arrived with bent corners"],
    ),
    "toys": (
        ["hours of family fun", "great for kids and adults", "high quality pieces", "easy to learn"],
        ["missing a piece", "instructions were unclear", "box arrived damaged"],
    ),
}
